# Generated by Django 4.2.5 on 2025-04-23 05:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='qr_refresh_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='member',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
