# Generated by Django 4.2.5 on 2025-04-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_member_profile_image_member_qr_refresh_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='member',
            name='qr_refresh_token',
        ),
        migrations.RemoveField(
            model_name='member',
            name='session_key',
        ),
    ]
